### ISSUE TITLE
Facebook Side Widget Not Working

### ISSUE THREAD

**Issue by GeniusMBM** [Kaelri/Enigma#104]
I'm running the latest stable version of Enigma version 4.1 and the latest stable version of Rainmeter 3.3.1 r2602 64-bit (Mar 18 2016) and the Facebook side widget has stopped working. The error given is "Waiting for data from WebParser.". It was working just before the update so it has only affected me after the update.

I checked the log and the message is as follows: "WebParser: (Fetch error) The URL does not use a recognised protocol (ErrorCode= 12006)".

Just to be sure I went through the instructions again going to www.facebook.com/notifications, going on RSS and then copying that link back but nothing changed, it still gave the same message. Does this mean the recognised protocol has changed and if so, what is the new protocol?

**Comment by raytrygstad** [comment]
I have the same issue except me error message reads:
**Invalid Feed Format**
Could not identify a valid feed format.

**Comment by znic1967** [comment]
I have the same issue. The via RSS button is no longer on my notifications page.

**Comment by saytr101** [comment]
I heard Facebook doesn't support RSS feeds anymore due to not enough demand for it.

**Comment by GeniusMBM** [comment]
I've given up hope and unloaded the Facebook skin along with the weather skin. At least the local information derived skins still work.

**Comment by saytr101** [comment]
I actually got the weather skin working with a fix around I found on Reddit if you're interested

Sent from my ASUS

-------- Original Message --------

**Comment by GeniusMBM** [comment]
@saytr101 for latest Enigma version running on Rainmeter 3.3.1 r2602? Sure, send it through!

**Comment by saytr101** [comment]
Here you go

https://www.reddit.com/r/Rainmeter/comments/4ggr2v/just_fixed_the_weather_api_problem_not_a_skin_dev/

**Comment by GeniusMBM** [comment]
Quick search and a viable solution has been found for the Yahoo weather: https://forum.rainmeter.net/viewtopic.php?p=125192#p125192

**Comment by saytr101** [comment]
I still don't understand why Facebook decided to stop RSS feeds.

**Comment by GeniusMBM** [comment]
Cost them resources they don't need I guess. I'm going to close this issue since Facebook no longer supports this function.
