### ISSUE TITLE
Windows 10 Defender False-Positive

### ISSUE THREAD

**Issue by Austemagne** [Kaelri/Enigma#110]
Windows Defender is flagging this as a severe threat. It might be prudent to appeal to Windows to have a human review this code and its purpose.

**Comment by malavv** [comment]
Same here, came in to make notify the team. When I click on download zip, windows does even let me get it. It removes it before its downloaded.

**Comment by mon0theist** [comment]
Malwarebytes is doing the same thing, can't run the weather code finder exe because malwarebytes just quarantines it
