### ISSUE TITLE
Cannot find download button

### ISSUE THREAD

**Issue by imnotjack91** [Kaelri/Enigma#118]
The deviant art link only took me to the project.... Where there is no download option that I can see.

**Comment by kaelri** [comment]
There are several options available to copy or download the code from the project homepage.

<img width="381" alt="Screen Shot 2020-12-17 at 8 38 38 AM" src="https://user-images.githubusercontent.com/826292/102494878-5e0f9c80-4043-11eb-9fa6-71ff58d50296.png">
