### ISSUE TITLE
Your Rainmeter Skins

### ISSUE THREAD

**Issue by Rainmeterbase** [Kaelri/Enigma#121]
Hello,
I saw your rainmeter skin called "Enigma" and liked it. I also have a site about [rainmeter skins](https://rainmeterbase.com/skins). Its address is [https://rainmeterbase.com](https://rainmeterbase.com) and I promote skins to Rainmeter users on this site. With your permission, may I introduce Enigma as well?

**Comment by kaelri** [comment]
Hi there — I would recommend against listing Enigma on your site, for the reasons described in the [deviantArt post](https://www.deviantart.com/kaelri/art/Enigma-103823591). That said, I wish you the best of luck with your new site!
