### ISSUE TITLE
Hide sidebar widget not working

### ISSUE THREAD

**Issue by IllidanStormrag3** [Kaelri/Enigma#122]
when I click on the "hide sidebar" widget it doesn't hide the side bars at all

**Comment by Pythbit** [comment]
Hey, I managed to fix this by going to Edit Skin and changing:
LeftMouseUpAction=[![#State1]FadeGroup EnigmaSidebar][!WriteKeyValue Variables State1 [#State2]][!WriteKeyValue Variables State2 [#State1]][!Refresh]
To
LeftMouseUpAction=[!ToggleFadeGroup EnigmaSidebar][!WriteKeyValue Variables State1 [#State2]][!WriteKeyValue Variables State2 [#State1]][!Refresh]

**Comment by IllidanStormrag3** [comment]
that fixed it, thanks a bunch
