### ISSUE TITLE
Weather Code Selector not working

### ISSUE THREAD

**Issue by dsgkirkby** [Kaelri/Enigma#31]
When I go to the weather code finder and type in my home city, it doesn't register it (i.e. when I press enter it reverts to what it was before) and the search list doesn't change from the various Londons worldwide.

**Comment by jeevadotnet** [comment]
I have the same problem. Rainmeter 3.3.0 Beta R2402

At first the options > world settings AND Enigma weather code finder, worked fine. 

After my first reboot I was unable to change anything except for "right click, defaults". 

Under ENIGMA WORLD, you get the "weather code" - "yourweathercodehere"., 1st world 2nd world, etc.  If i click on any of the variables the ENIGE WEATHER CODE FINDER COMES up. Here i'm unable to add or remove anything. It just shows "Madison - Maine - United States", which was one of my original 3 worlds. I can only click "Set & Copy" but not change anything.

Regards

**Comment by exhibitO** [comment]
Showing up as detection in Malaware bytes.
