### ISSUE TITLE
Calendar has problem with November 

### ISSUE THREAD

**Issue by michalk0** [Kaelri/Enigma#83]
I have just installed Enigma and when attempting to use calendar it did not show. 
I found that solution presented here  (problem specific for November as calendar 
for December was displayed properly )
http://comments.deviantart.com/1/103823591/2806248037 
works for me. 

The problem from log was something like 
enigma script calendar.lua at line 204 invalid value (nil) at index 3 in table for concat

Version I use: 
3.2.0 beta r2326 64-bit (Sep 17 2014)
Windows 8.1 64-bit (build 9600)

Best regards,
michalk0

**Comment by betacris** [comment]
Worked for me. Thanks!
https://github.com/Kaelri/Enigma/commit/2afbb369e14b6615d74c6b583294eb86d502e87e

**Comment by Gamerbiomek2** [comment]
Numbers not showing in calender
